### ISSUE TITLE
I think this modnOnly is a typo

### ISSUE THREAD

**Issue by slipperygun** [Coding-World-Discord/Coding_World#1]
https://github.com/Coding-World-Discord/Coding_World/blob/644a92b540211ff0b0250e8230e6f995aa80b77d/src/monitors/commands/commandHandler.ts#L30

**Comment by koreanpanda345** [comment]
Oh it is lol

**Comment by slipperygun** [comment]
> Oh it is lol

at least it was also misspelled where it counted so I think it still worked.
